# Generated by Django 4.1 on 2022-08-05 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(max_length=30)),
                ('element_id', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
                ('pos', models.IntegerField()),
                ('fk_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugSquash.routine')),
            ],
        ),
    ]
