# Generated by Django 4.1 on 2022-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugSquash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='url',
            field=models.CharField(default='tet', max_length=256),
            preserve_default=False,
        ),
    ]
