# Generated by Django 4.1 on 2022-08-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugSquash', '0002_routine_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='fk_test',
            new_name='fk_routine',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='content',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
