# Generated by Django 4.1 on 2022-08-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugSquash', '0003_rename_fk_test_interaction_fk_routine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='content',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
